# build_report.py
#
# Builds the multi-dataset Q-head report as one self-contained HTML file with
# inline SVG charts and embedded example images. Every number is read from the
# sweep outputs (q_models/<dataset>/*.json), the per-dataset analysis files
# (results/analysis_<dataset>.json), and the original ChartQA study report
# (results/confidence_comparison_report.html), so rerunning it after new
# experiments refreshes the whole report. Compute times are the only
# hand-entered values.

import html
import json
import re
from pathlib import Path

HERE = Path(__file__).parent
OUTPUT = HERE / "results" / "q_head_multidataset_report.html"
ORIGINAL_REPORT = HERE / "results" / "confidence_comparison_report.html"
ORIGINAL_RUNS_JSON = HERE / "results" / "chartqa_original_validation_runs.json"

DATASETS = [
    ("chartqa_full", "ChartQA", "charts"),
    ("textvqa", "TextVQA", "scene text"),
    ("docvqa", "DocVQA", "documents"),
    ("scienceqa_img", "ScienceQA", "science diagrams"),
]
SCORERS = [
    ("token_confidence", "Token confidence", "c-tok"),
    ("separate_pre_generation", "Separate pre-gen head", "c-sp"),
    ("separate_verifier", "Separate verifier head", "c-sv"),
    ("unified_pre_generation", "Unified, pre-gen mode", "c-up"),
    ("unified_joint", "Unified, joint mode", "c-uj"),
]
SCORER_LABEL = {key: label for key, label, _ in SCORERS}
SCORER_CLASS = {key: css for key, _, css in SCORERS}
METRICS = [
    ("correctness_auroc", "Correctness AUROC", "higher"),
    ("error_auprc", "Error AUPRC", "higher"),
    ("brier", "Brier score", "lower"),
    ("ece_10_bin", "ECE (10 bins)", "lower"),
    ("pearson_correctness", "Pearson r", "higher"),
]
# Test table from the original ChartQA study report, 2,500 test questions.
ORIGINAL_COLUMNS = [
    ("Geometric-mean token confidence", "c-tok"),
    ("Pre-gen MLP", "c-sp"),
    ("Pre-gen linear probe", "c-w1"),
    ("Verifier MLP (swept)", "c-sv"),
    ("Verifier, early stop (3 seeds)", "c-up"),
]
ORIGINAL_TEST = {
    "Correctness AUROC": ["0.750", "0.863", "0.895", "0.887", "0.891 ± 0.001"],
    "Error AUPRC": ["0.583", "0.669", "0.732", "0.723", "0.738 ± 0.005"],
    "Brier score": ["0.178", "0.123", "0.109", "0.112", "0.111 ± 0.001"],
    "ECE (10 bins)": ["0.172", "0.055", "0.036", "0.030", "0.038 ± 0.014"],
    "Accuracy at 50% coverage": ["92.40%", "95.12%", "97.04%", "96.64%", "97.04%"],
}
# Wall-clock minutes from Slurm accounting on one L40S GPU: build or download, train baseline, train features.
COMPUTE_MINUTES = {
    "textvqa": (49.7, 24.6, 28.4),
    "docvqa": (67.9, 39.7, 62.8),
    "scienceqa_img": (2.7, 8.0, 11.8),
}
COMPUTE_FILE = HERE / "results" / "compute_minutes.json"

DATASET_INFO = {
    "chartqa_full": {
        "source": "HuggingFaceM4/ChartQA",
        "what": "Questions about bar, line, and pie charts, written by people and generated by templates. Answers are numbers or short text read or computed from the chart.",
        "rule": "Relaxed accuracy: a numeric answer within 5% of the reference counts as correct, text answers need a normalized exact match.",
        "why": "The dataset of the original study, kept as the common reference point.",
        "splits": "Official train, validation, and test splits.",
    },
    "textvqa": {
        "source": "lmms-lab/textvqa (TextVQA, photographs from Open Images)",
        "what": "Questions that can only be answered by reading text inside a photograph: the brand on a watch, the number on a jersey, what a shirt says. Each question has 10 human answers, which disagree often enough that correctness is a matter of degree.",
        "rule": "Official VQA soft accuracy over the 10 answers. An answer is labeled correct when the score is 0.5 or more, which needs at least two annotators to agree with it.",
        "why": "Tests a different visual skill (reading small, partial, or stylized text in clutter) and free-form answers with natural annotator disagreement.",
        "splits": "8,000 training questions sampled from the official train split (34,602). Validation (1,500) and test (2,500) are carved out of the labeled official validation split by image, because official test answers are hidden.",
    },
    "docvqa": {
        "source": "HuggingFaceM4/DocumentVQA (DocVQA, UCSF Industry Documents Library)",
        "what": "Questions about scanned pages from industry documents: letters, forms, reports, tables, handwritten notes. Answers are spans copied from the page. Each question carries a type such as table or list, layout, form, free text, handwritten, or figure or diagram.",
        "rule": "ANLS similarity (one minus normalized edit distance to the closest reference). An answer is labeled correct at 0.9 or more, stricter than the 0.5 cutoff used in the official leaderboard.",
        "why": "Dense text at high resolution, long documents, and answers that must match a span exactly, which is very unlike a chart or a photograph.",
        "splits": "8,000 training questions sampled from the official train split (39,463). Validation (1,500) and test (2,500) are carved out of the labeled official validation split by document, because official test answers are hidden. Page images are capped at 1,536 pixels on the long side.",
    },
    "scienceqa_img": {
        "source": "derek-thomas/ScienceQA (image questions only)",
        "what": "Grade-school science questions with a picture or diagram, such as maps, genetics crosses, animal classification, experiments, and reading passages. Every question is multiple choice and the model answers with an option letter.",
        "rule": "Exact match on the option letter, parsed from the first letter of the reply.",
        "why": "A closed answer set, so the answer itself carries almost no information. It tests whether a correctness head still helps when there is little to read in the answer.",
        "splits": "Official train, validation, and test splits, restricted to questions that have an image.",
    },
}


def esc(value) -> str:
    """Escape text for HTML."""
    return html.escape(str(value))


def parse_original_runs(path: Path) -> list[dict]:
    """Read the 72 validation runs out of the original study report's raw sweep table."""
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    runs = []
    for row in re.findall(r"<tr>(.*?)</tr>", text, flags=re.S):
        cells = [re.sub(r"<[^>]+>", "", c).strip() for c in re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", row, flags=re.S)]
        if len(cells) >= 11 and cells[0] in ("Pre-generation", "Candidate verifier"):
            runs.append(
                {
                    "head": "pre_generation" if cells[0] == "Pre-generation" else "verifier",
                    "architecture": cells[1],
                    "learning_rate": cells[2],
                    "ranking_weight": float(cells[3]),
                    "seed": int(cells[4]),
                    "error_auprc": float(cells[5]),
                    "auroc": float(cells[6]),
                    "brier": float(cells[7]),
                    "ece": float(cells[8]),
                    "pearson": float(cells[9]),
                }
            )
    return runs


def load_dataset_results(key: str) -> dict | None:
    """Load sweep and analysis files for one dataset, or None if any are missing."""
    folder = HERE / "q_models" / key
    analysis = HERE / "results" / f"analysis_{key}.json"
    files = (folder / "sweep_results.json", folder / "unified_sweep_results.json", analysis)
    if not all(path.exists() for path in files):
        return None
    separate, unified, extra = (json.loads(path.read_text(encoding="utf-8")) for path in files)
    metrics = {
        "token_confidence": {name: (extra["token_confidence_metrics"][name], None) for name, _, _ in METRICS},
        "separate_pre_generation": {
            name: (separate["pre_generation"]["test"][name], None) for name, _, _ in METRICS
        },
        "separate_verifier": {
            name: (separate["candidate_verifier"]["test"][name], None) for name, _, _ in METRICS
        },
    }
    for scorer, mode in (("unified_pre_generation", "pre_generation"), ("unified_joint", "joint")):
        metrics[scorer] = {
            name: (unified["test_summary"][mode][name]["mean"], unified["test_summary"][mode][name]["std"])
            for name, _, _ in METRICS
        }
    return {"separate": separate, "unified": unified, "analysis": extra, "metrics": metrics}


def f3(value: float) -> str:
    """Format a metric to three decimals."""
    return f"{value:.3f}"


def pct(value: float, digits: int = 1) -> str:
    """Format a fraction as a percentage."""
    return f"{100 * value:.{digits}f}%"


def cell(pair: tuple) -> str:
    """Format a (mean, std) pair, hiding the spread for single runs."""
    mean, std = pair
    return f3(mean) if std is None else f"{f3(mean)} ± {f3(std)}"


# ---------------------------------------------------------------- charts


class Panel:
    """Linear scales and axis drawing for one chart area inside an SVG."""

    def __init__(self, x0, y0, width, height, xmin, xmax, ymin, ymax):
        self.x0, self.y0, self.w, self.h = x0, y0, width, height
        self.xmin, self.xmax, self.ymin, self.ymax = xmin, xmax, ymin, ymax

    def sx(self, value: float) -> float:
        """Map a data x value to SVG x."""
        return self.x0 + (value - self.xmin) / (self.xmax - self.xmin) * self.w

    def sy(self, value: float) -> float:
        """Map a data y value to SVG y."""
        return self.y0 + self.h - (value - self.ymin) / (self.ymax - self.ymin) * self.h

    def axes(self, xticks, yticks, xfmt=lambda v: f"{v:g}", yfmt=lambda v: f"{v:g}", xlabel="", ylabel="") -> str:
        """Draw gridlines, tick labels, and axis titles."""
        parts = []
        for tick in yticks:
            y = self.sy(tick)
            parts.append(f'<line class="grid" x1="{self.x0}" x2="{self.x0 + self.w}" y1="{y:.1f}" y2="{y:.1f}"/>')
            parts.append(f'<text class="tick" x="{self.x0 - 6}" y="{y + 3.5:.1f}" text-anchor="end">{yfmt(tick)}</text>')
        for tick in xticks:
            x = self.sx(tick)
            parts.append(f'<text class="tick" x="{x:.1f}" y="{self.y0 + self.h + 15}" text-anchor="middle">{xfmt(tick)}</text>')
        parts.append(f'<line class="axis" x1="{self.x0}" x2="{self.x0 + self.w}" y1="{self.y0 + self.h}" y2="{self.y0 + self.h}"/>')
        if xlabel:
            parts.append(f'<text class="axlabel" x="{self.x0 + self.w / 2}" y="{self.y0 + self.h + 32}" text-anchor="middle">{esc(xlabel)}</text>')
        if ylabel:
            parts.append(
                f'<text class="axlabel" transform="rotate(-90)" x="{-(self.y0 + self.h / 2)}" y="{self.x0 - 38}" text-anchor="middle">{esc(ylabel)}</text>'
            )
        return "".join(parts)


def legend(items) -> str:
    """HTML legend with a swatch per series, for charts with two or more series."""
    swatches = "".join(
        f'<span class="lg"><svg width="22" height="10" viewBox="0 0 22 10" aria-hidden="true">'
        f'<line class="{css} ln" x1="1" x2="21" y1="5" y2="5"/><circle class="{css} dot" cx="11" cy="5" r="3.5"/></svg>{esc(label)}</span>'
        for label, css in items
    )
    return f'<div class="legend">{swatches}</div>'


def scorer_legend() -> str:
    """Legend covering all five scorers."""
    return legend([(label, css) for _, label, css in SCORERS])


def dot_plot(rows, series, xmin: float, xmax: float, xlabel: str, chance=None, caption_id="") -> str:
    """One row per group, one dot per series, with an optional chance marker per row."""
    row_h, left, top = 14 * len(series) // 2 + 34, 150, 8
    height = top + row_h * len(rows) + 40
    panel = Panel(left, top, 640 - left - 16, row_h * len(rows), xmin, xmax, 0, 1)
    parts = [f'<svg viewBox="0 0 640 {height}" role="img" aria-labelledby="{caption_id}">']
    ticks = [round(xmin + i * (xmax - xmin) / 5, 3) for i in range(6)]
    for tick in ticks:
        parts.append(f'<line class="grid" x1="{panel.sx(tick):.1f}" x2="{panel.sx(tick):.1f}" y1="{top}" y2="{top + row_h * len(rows)}"/>')
        parts.append(f'<text class="tick" x="{panel.sx(tick):.1f}" y="{top + row_h * len(rows) + 15}" text-anchor="middle">{tick:g}</text>')
    parts.append(f'<text class="axlabel" x="{left + panel.w / 2}" y="{top + row_h * len(rows) + 33}" text-anchor="middle">{esc(xlabel)}</text>')
    spread = 9
    for index, (name, values) in enumerate(rows):
        yc = top + row_h * index + row_h / 2
        parts.append(f'<text class="rowlabel" x="{left - 10}" y="{yc + 4:.1f}" text-anchor="end">{esc(name)}</text>')
        if index:
            parts.append(f'<line class="grid" x1="{left}" x2="{left + panel.w}" y1="{top + row_h * index}" y2="{top + row_h * index}"/>')
        if chance and chance.get(name) is not None:
            x = panel.sx(chance[name])
            parts.append(f'<line class="chance" x1="{x:.1f}" x2="{x:.1f}" y1="{yc - row_h / 2 + 6:.1f}" y2="{yc + row_h / 2 - 6:.1f}"><title>{esc(name)} chance level {chance[name]:.3f}</title></line>')
        for offset, (scorer, label, css) in enumerate(series):
            if scorer not in values:
                continue
            y = yc + (offset - (len(series) - 1) / 2) * spread
            parts.append(
                f'<circle class="{css} dot" cx="{panel.sx(values[scorer]):.1f}" cy="{y:.1f}" r="4.2"><title>{esc(name)}, {esc(label)}: {values[scorer]:.3f}</title></circle>'
            )
    parts.append("</svg>")
    return "".join(parts)


def strip_plot(rows, xmin: float, xmax: float, xlabel: str, caption_id="") -> str:
    """One row per group, with one dot per run. Each point is (value, css class, tooltip)."""
    row_h, left, top = 40, 170, 8
    height = top + row_h * len(rows) + 40
    panel = Panel(left, top, 640 - left - 16, row_h * len(rows), xmin, xmax, 0, 1)
    parts = [f'<svg viewBox="0 0 640 {height}" role="img" aria-labelledby="{caption_id}">']
    for i in range(6):
        tick = xmin + i * (xmax - xmin) / 5
        parts.append(f'<line class="grid" x1="{panel.sx(tick):.1f}" x2="{panel.sx(tick):.1f}" y1="{top}" y2="{top + row_h * len(rows)}"/>')
        parts.append(f'<text class="tick" x="{panel.sx(tick):.1f}" y="{top + row_h * len(rows) + 15}" text-anchor="middle">{tick:.3f}</text>')
    parts.append(f'<text class="axlabel" x="{left + panel.w / 2}" y="{top + row_h * len(rows) + 33}" text-anchor="middle">{esc(xlabel)}</text>')
    for index, (name, points) in enumerate(rows):
        yc = top + row_h * index + row_h / 2
        parts.append(f'<text class="rowlabel" x="{left - 10}" y="{yc + 4:.1f}" text-anchor="end">{esc(name)}</text>')
        if index:
            parts.append(f'<line class="grid" x1="{left}" x2="{left + panel.w}" y1="{top + row_h * index}" y2="{top + row_h * index}"/>')
        for rank, (value, css, tip) in enumerate(points):
            y = yc + ((rank % 3) - 1) * 8
            parts.append(f'<circle class="{css} dot" cx="{panel.sx(value):.1f}" cy="{y:.1f}" r="3.8" fill-opacity=".9"><title>{esc(tip)}</title></circle>')
    parts.append("</svg>")
    return "".join(parts)


def delta_plot(entries, caption_id="") -> str:
    """Dots with 95% interval whiskers for a paired difference, with a zero line."""
    values = [v for _, _, d, lo, hi in entries for v in (d, lo, hi)]
    limit = max(abs(min(values)), abs(max(values))) * 1.15
    row_h, left, top = 30, 190, 8
    height = top + row_h * len(entries) + 40
    panel = Panel(left, top, 640 - left - 20, row_h * len(entries), -limit, limit, 0, 1)
    parts = [f'<svg viewBox="0 0 640 {height}" role="img" aria-labelledby="{caption_id}">']
    steps = 4
    for i in range(steps * 2 + 1):
        tick = -limit + i * (2 * limit) / (steps * 2)
        parts.append(f'<line class="grid" x1="{panel.sx(tick):.1f}" x2="{panel.sx(tick):.1f}" y1="{top}" y2="{top + row_h * len(entries)}"/>')
        parts.append(f'<text class="tick" x="{panel.sx(tick):.1f}" y="{top + row_h * len(entries) + 15}" text-anchor="middle">{tick:+.3f}</text>')
    parts.append(f'<line class="axis" x1="{panel.sx(0):.1f}" x2="{panel.sx(0):.1f}" y1="{top}" y2="{top + row_h * len(entries)}"/>')
    parts.append(f'<text class="axlabel" x="{left + panel.w / 2}" y="{top + row_h * len(entries) + 33}" text-anchor="middle">Unified minus separate head, correctness AUROC</text>')
    for index, (dataset, comparison, difference, low, high) in enumerate(entries):
        yc = top + row_h * index + row_h / 2
        css = "c-uj" if comparison == "joint" else "c-up"
        parts.append(f'<text class="rowlabel" x="{left - 10}" y="{yc + 4:.1f}" text-anchor="end">{esc(dataset)}, {comparison} mode</text>')
        parts.append(f'<line class="{css} ln" x1="{panel.sx(low):.1f}" x2="{panel.sx(high):.1f}" y1="{yc:.1f}" y2="{yc:.1f}"/>')
        parts.append(
            f'<circle class="{css} dot" cx="{panel.sx(difference):.1f}" cy="{yc:.1f}" r="4.5"><title>{esc(dataset)} {comparison}: {difference:+.4f} (95% CI {low:+.4f} to {high:+.4f})</title></circle>'
        )
    parts.append("</svg>")
    return "".join(parts)


def line_panel(title: str, grid, series, ymin, ymax, ytick_step, xlabel, ylabel, diagonal=False) -> str:
    """Small line chart with one polyline and marker set per scorer."""
    width, height = 340, 250
    panel = Panel(48, 12, width - 62, height - 56, 0, 1, ymin, ymax)
    yticks = []
    tick = ymin
    while tick <= ymax + 1e-9:
        yticks.append(round(tick, 3))
        tick += ytick_step
    parts = [f'<svg viewBox="0 0 {width} {height}" role="img" aria-label="{esc(title)}">']
    parts.append(panel.axes([0, 0.25, 0.5, 0.75, 1], yticks, xfmt=lambda v: f"{v:g}", yfmt=lambda v: f"{v:g}", xlabel=xlabel, ylabel=ylabel))
    if diagonal:
        parts.append(f'<line class="chance" x1="{panel.sx(0):.1f}" y1="{panel.sy(ymin):.1f}" x2="{panel.sx(1):.1f}" y2="{panel.sy(ymax):.1f}"/>')
    for scorer, xs, ys in series:
        css = SCORER_CLASS[scorer]
        points = " ".join(f"{panel.sx(x):.1f},{panel.sy(y):.1f}" for x, y in zip(xs, ys))
        parts.append(f'<polyline class="{css} ln" points="{points}" fill="none"/>')
        for x, y in list(zip(xs, ys))[:: max(1, len(xs) // 10)]:
            parts.append(
                f'<circle class="{css} dot" cx="{panel.sx(x):.1f}" cy="{panel.sy(y):.1f}" r="2.8"><title>{esc(title)}, {esc(SCORER_LABEL[scorer])}: x={x:.2f}, y={y:.3f}</title></circle>'
            )
    parts.append("</svg>")
    return f'<figure class="panel"><figcaption>{esc(title)}</figcaption>{"".join(parts)}</figure>'


def hist_panel(title: str, histogram: dict) -> str:
    """Overlaid step outlines of the predicted-correctness distribution for right and wrong answers."""
    width, height = 340, 250
    correct = histogram["correct"]
    wrong = histogram["wrong"]
    total_c, total_w = sum(correct) or 1, sum(wrong) or 1
    share_c = [c / total_c for c in correct]
    share_w = [w / total_w for w in wrong]
    top = max(share_c + share_w) * 1.1
    panel = Panel(48, 12, width - 62, height - 56, 0, 1, 0, top)
    ticks = [round(top * i / 4, 2) for i in range(5)]
    parts = [f'<svg viewBox="0 0 {width} {height}" role="img" aria-label="{esc(title)}">']
    parts.append(panel.axes([0, 0.25, 0.5, 0.75, 1], ticks, yfmt=lambda v: f"{v:.2f}", xlabel="Predicted probability of correct", ylabel="Share of class"))
    edges = histogram["edges"]
    for shares, css, label in ((share_w, "c-bad", "wrong answers"), (share_c, "c-ok", "correct answers")):
        path = []
        for index, share in enumerate(shares):
            x0, x1 = panel.sx(edges[index]), panel.sx(edges[index + 1])
            path.append(f"{x0:.1f},{panel.sy(share):.1f} {x1:.1f},{panel.sy(share):.1f}")
        parts.append(f'<polyline class="{css} ln" fill="none" points="{" ".join(path)}"/>')
        for index, share in enumerate(shares):
            xm = (panel.sx(edges[index]) + panel.sx(edges[index + 1])) / 2
            parts.append(f'<circle class="{css} dot hit" cx="{xm:.1f}" cy="{panel.sy(share):.1f}" r="3"><title>{esc(label)}, bin {edges[index]:.2f} to {edges[index + 1]:.2f}: {pct(share)}</title></circle>')
    parts.append("</svg>")
    return f'<figure class="panel"><figcaption>{esc(title)}</figcaption>{"".join(parts)}</figure>'


def category_chart(rows, caption_id="") -> str:
    """Dumbbell chart of observed accuracy against mean predicted correctness per category."""
    row_h, left, top = 26, 215, 8
    height = top + row_h * len(rows) + 40
    xmin, xmax = 0.6, 1.0
    panel = Panel(left, top, 640 - left - 20, row_h * len(rows), xmin, xmax, 0, 1)
    parts = [f'<svg viewBox="0 0 640 {height}" role="img" aria-labelledby="{caption_id}">']
    for i in range(5):
        tick = xmin + i * (xmax - xmin) / 4
        parts.append(f'<line class="grid" x1="{panel.sx(tick):.1f}" x2="{panel.sx(tick):.1f}" y1="{top}" y2="{top + row_h * len(rows)}"/>')
        parts.append(f'<text class="tick" x="{panel.sx(tick):.1f}" y="{top + row_h * len(rows) + 15}" text-anchor="middle">{tick:.2f}</text>')
    parts.append(f'<text class="axlabel" x="{left + panel.w / 2}" y="{top + row_h * len(rows) + 33}" text-anchor="middle">Observed accuracy (dark) and mean predicted correctness (blue)</text>')
    for index, (label, accuracy, predicted) in enumerate(rows):
        yc = top + row_h * index + row_h / 2
        parts.append(f'<text class="rowlabel" x="{left - 10}" y="{yc + 4:.1f}" text-anchor="end">{esc(label)}</text>')
        parts.append(f'<line class="gap" x1="{panel.sx(accuracy):.1f}" x2="{panel.sx(predicted):.1f}" y1="{yc:.1f}" y2="{yc:.1f}"/>')
        parts.append(f'<circle class="c-acc dot" cx="{panel.sx(accuracy):.1f}" cy="{yc:.1f}" r="4.5"><title>{esc(label)} observed accuracy {accuracy:.3f}</title></circle>')
        parts.append(f'<circle class="c-uj dot" cx="{panel.sx(predicted):.1f}" cy="{yc:.1f}" r="4.5"><title>{esc(label)} mean predicted {predicted:.3f}</title></circle>')
    parts.append("</svg>")
    return "".join(parts)


def ablation_plot(rows, caption_id="") -> str:
    """Dot chart of the best validation AUROC reached at each pre-generation loss weight."""
    row_h, left, top = 52, 112, 8
    values = [v for _, series in rows for v in series.values()]
    xmin, xmax = min(values) - 0.01, max(values) + 0.01
    height = top + row_h * len(rows) + 40
    panel = Panel(left, top, 640 - left - 16, row_h * len(rows), xmin, xmax, 0, 1)
    parts = [f'<svg viewBox="0 0 640 {height}" role="img" aria-labelledby="{caption_id}">']
    for i in range(6):
        tick = xmin + i * (xmax - xmin) / 5
        parts.append(f'<line class="grid" x1="{panel.sx(tick):.1f}" x2="{panel.sx(tick):.1f}" y1="{top}" y2="{top + row_h * len(rows)}"/>')
        parts.append(f'<text class="tick" x="{panel.sx(tick):.1f}" y="{top + row_h * len(rows) + 15}" text-anchor="middle">{tick:.3f}</text>')
    parts.append(f'<text class="axlabel" x="{left + panel.w / 2}" y="{top + row_h * len(rows) + 33}" text-anchor="middle">Validation AUROC of the pre-generation mode (best config at each weight)</text>')
    css_for = {0.0: "c-w0", 0.5: "c-w1", 1.0: "c-w2"}
    for index, (name, series) in enumerate(rows):
        yc = top + row_h * index + row_h / 2
        parts.append(f'<text class="rowlabel" x="{left - 10}" y="{yc + 4:.1f}" text-anchor="end">{esc(name)}</text>')
        if index:
            parts.append(f'<line class="grid" x1="{left}" x2="{left + panel.w}" y1="{top + row_h * index}" y2="{top + row_h * index}"/>')
        for offset, (weight, value) in enumerate(sorted(series.items())):
            parts.append(
                f'<circle class="{css_for[weight]} dot" cx="{panel.sx(value):.1f}" cy="{yc + (offset - 1) * 11:.1f}" r="4.5"><title>{esc(name)}, pre weight {weight:g}: {value:.4f}</title></circle>'
            )
    parts.append("</svg>")
    return "".join(parts)


def pipeline_diagram() -> str:
    """Flow diagram from input to correctness score to the planned correction step."""
    boxes = [
        (10, "Image and question", "input", ""),
        (170, "Qwen3-VL-2B", "frozen, no updates", ""),
        (330, "Two cached states", "prompt state, answer state", ""),
        (490, "Q-head", "small trained network", "hl"),
        (650, "Correctness score", "probability answer is right", ""),
        (810, "Gate, then correct", "planned next stage", "future"),
    ]
    parts = ['<svg viewBox="0 0 960 112" role="img" aria-labelledby="fig-pipeline">']
    for index, (x, title, sub, kind) in enumerate(boxes):
        parts.append(f'<rect class="box {kind}" x="{x}" y="22" width="140" height="68" rx="8"/>')
        parts.append(f'<text class="boxt" x="{x + 70}" y="53" text-anchor="middle">{esc(title)}</text>')
        parts.append(f'<text class="boxs" x="{x + 70}" y="72" text-anchor="middle">{esc(sub)}</text>')
        if index < len(boxes) - 1:
            parts.append(f'<path class="arrow" d="M{x + 142} 56 L{x + 158} 56"/><path class="arrowhead" d="M{x + 158} 52 L{x + 166} 56 L{x + 158} 60 z"/>')
    parts.append("</svg>")
    return "".join(parts)


def unified_diagram() -> str:
    """Block diagram of the unified head with its two input latents, flag bit, and two modes."""
    parts = ['<svg viewBox="0 0 900 250" role="img" aria-labelledby="fig-unified">']

    def box(x, y, w, h, title, sub="", kind=""):
        out = f'<rect class="box {kind}" x="{x}" y="{y}" width="{w}" height="{h}" rx="8"/>'
        out += f'<text class="boxt" x="{x + w / 2}" y="{y + h / 2 - (4 if sub else -4)}" text-anchor="middle">{esc(title)}</text>'
        if sub:
            out += f'<text class="boxs" x="{x + w / 2}" y="{y + h / 2 + 14}" text-anchor="middle">{esc(sub)}</text>'
        return out

    def arrow(x1, y1, x2, y2):
        dx, dy = x2 - x1, y2 - y1
        length = (dx * dx + dy * dy) ** 0.5
        ux, uy = dx / length, dy / length
        bx, by = x2 - 8 * ux, y2 - 8 * uy
        head = f"M{x2} {y2} L{bx - 4 * uy:.1f} {by + 4 * ux:.1f} L{bx + 4 * uy:.1f} {by - 4 * ux:.1f} z"
        return f'<path class="arrow" d="M{x1} {y1} L{bx:.1f} {by:.1f}"/><path class="arrowhead" d="{head}"/>'

    parts.append(box(10, 30, 170, 56, "Prompt latent", "last prompt token, d = 2048"))
    parts.append(box(10, 150, 170, 56, "Answer latent", "last answer token, d = 2048", "opt"))
    parts.append(box(235, 30, 120, 56, "LayerNorm"))
    parts.append(box(235, 150, 120, 56, "LayerNorm", "", "opt"))
    parts.append(box(410, 70, 150, 100, "Concat", "prompt | answer | flag", "hl"))
    parts.append(box(615, 70, 130, 100, "Linear or MLP", "one logit"))
    parts.append(box(790, 70, 100, 100, "Score", "P(correct)"))
    parts.append(arrow(180, 58, 235, 58) + arrow(355, 58, 410, 100) + arrow(180, 178, 235, 178) + arrow(355, 178, 410, 140))
    parts.append(arrow(560, 120, 615, 120) + arrow(745, 120, 790, 120))
    parts.append('<text class="note" x="590" y="30" text-anchor="middle">Joint mode: answer present, flag = 1</text>')
    parts.append('<text class="note" x="590" y="48" text-anchor="middle">Pre-generation mode: answer half zeroed, flag = 0</text>')
    parts.append("</svg>")
    return "".join(parts)


# ---------------------------------------------------------------- page


CSS = """
:root{color-scheme:light;--bg:#f9f9f7;--surface:#fcfcfb;--ink:#0b0b0b;--ink2:#52514e;--muted:#898781;--grid:#e1e0d9;--axis:#c3c2b7;
--line:rgba(11,11,11,.10);--tok:#898781;--sp:#eda100;--sv:#eb6834;--up:#1baf7a;--uj:#2a78d6;--accent:#184f95;--good:#006300;--soft:#eef3fb;--ok:#008300;--bad:#e34948;--w0:#9ec5f4;--w1:#5598e7;--w2:#184f95}
@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){color-scheme:dark;--bg:#0d0d0d;--surface:#1a1a19;--ink:#fff;--ink2:#c3c2b7;
--muted:#898781;--grid:#2c2c2a;--axis:#383835;--line:rgba(255,255,255,.10);--sp:#c98500;--sv:#d95926;--up:#199e70;--uj:#3987e5;--accent:#86b6ef;--good:#0ca30c;--soft:#202733;--ok:#008300;--bad:#e66767;--w0:#184f95;--w1:#3987e5;--w2:#9ec5f4}}
:root[data-theme="dark"]{color-scheme:dark;--bg:#0d0d0d;--surface:#1a1a19;--ink:#fff;--ink2:#c3c2b7;--muted:#898781;--grid:#2c2c2a;--axis:#383835;
--line:rgba(255,255,255,.10);--sp:#c98500;--sv:#d95926;--up:#199e70;--uj:#3987e5;--accent:#86b6ef;--good:#0ca30c;--soft:#202733;--ok:#008300;--bad:#e66767;--w0:#184f95;--w1:#3987e5;--w2:#9ec5f4}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.65 system-ui,-apple-system,"Segoe UI",sans-serif}
main{max-width:980px;margin:0 auto;padding:40px 20px 80px}
h1{font-size:2rem;line-height:1.2;margin:0 0 8px}h2{font-size:1.45rem;margin:52px 0 8px;padding-top:14px;border-top:1px solid var(--line)}
h3{font-size:1.08rem;margin:30px 0 6px}h4{font-size:.98rem;margin:20px 0 4px;color:var(--ink2)}p{margin:10px 0}.sub{color:var(--ink2);margin:0 0 24px}
.meta{color:var(--muted);font-size:.9rem}ul,ol{padding-left:22px}li{margin:6px 0}
.toc{display:flex;flex-wrap:wrap;gap:6px 18px;font-size:.92rem;margin:14px 0 4px}.toc a{color:var(--accent);text-decoration:none}.toc a:hover{text-decoration:underline}
.card{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:18px 20px;margin:16px 0}
.summary{background:var(--soft);border-color:transparent}
table{border-collapse:collapse;width:100%;font-size:.92rem;margin:12px 0}th,td{padding:7px 10px;border-bottom:1px solid var(--line);text-align:right;vertical-align:top}
th:first-child,td:first-child{text-align:left}th{font-weight:600;color:var(--ink2)}tr.best td{font-weight:600}td.l,th.l{text-align:left}
.tablewrap{overflow-x:auto}
figure{margin:16px 0}figure.wide{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:14px 14px 8px}
figcaption{font-weight:600;font-size:.95rem;margin:0 0 4px}.fignote{color:var(--ink2);font-size:.9rem;margin:6px 2px 0}
svg{width:100%;height:auto;display:block}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.panel{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:10px 10px 4px;margin:0}
@media(max-width:700px){.grid2{grid-template-columns:1fr}.dcard{grid-template-columns:1fr!important}}
.legend{display:flex;flex-wrap:wrap;gap:6px 16px;font-size:.88rem;color:var(--ink2);margin:6px 2px 8px}.lg{display:inline-flex;align-items:center;gap:6px}.lg svg{width:22px;height:10px;flex:none}
.grid{stroke:var(--grid);stroke-width:1}.axis{stroke:var(--axis);stroke-width:1}.chance{stroke:var(--muted);stroke-width:1.5;stroke-dasharray:4 3}
.gap{stroke:var(--axis);stroke-width:2}.tick{fill:var(--muted);font-size:11px}.axlabel{fill:var(--ink2);font-size:11.5px}.rowlabel{fill:var(--ink);font-size:12.5px}
.c-tok{--c:var(--tok)}.c-sp{--c:var(--sp)}.c-sv{--c:var(--sv)}.c-up{--c:var(--up)}.c-uj{--c:var(--uj)}.c-ok{--c:var(--ok)}.c-bad{--c:var(--bad)}.c-acc{--c:var(--ink)}.c-w0{--c:var(--w0)}.c-w1{--c:var(--w1)}.c-w2{--c:var(--w2)}
.ln{stroke:var(--c);stroke-width:2;stroke-linejoin:round;stroke-linecap:round}.dot{fill:var(--c);stroke:var(--surface);stroke-width:1.5}.dot.hit{fill-opacity:0;stroke:none;pointer-events:all}
.box{fill:var(--surface);stroke:var(--axis);stroke-width:1.5}.box.hl{stroke:var(--uj);stroke-width:2.5}.box.opt{stroke-dasharray:5 3}.box.future{stroke-dasharray:5 3;stroke:var(--muted)}
.boxt{fill:var(--ink);font-size:13px;font-weight:600}.boxs{fill:var(--ink2);font-size:11px}.note{fill:var(--ink2);font-size:12px}
.arrow{stroke:var(--muted);stroke-width:1.8;fill:none}.arrowhead{fill:var(--muted)}
code{font:.88em ui-monospace,Consolas,monospace;background:var(--soft);padding:1px 5px;border-radius:4px}
pre{background:var(--soft);padding:12px 14px;border-radius:8px;overflow-x:auto;font:.85rem/1.5 ui-monospace,Consolas,monospace}
.pos{color:var(--good);font-weight:600}.small{font-size:.9rem;color:var(--ink2)}
.dcard{display:grid;grid-template-columns:minmax(0,260px) 1fr;gap:18px;align-items:start}
.thumb{width:100%;height:auto;border-radius:8px;border:1px solid var(--line);display:block;background:#fff}
.stats{display:flex;flex-wrap:wrap;gap:8px 22px;margin:10px 0}.stat{min-width:110px}.stat b{display:block;font-size:1.25rem;line-height:1.2}.stat span{font-size:.8rem;color:var(--ink2)}
.case{border:1px solid var(--line);border-radius:10px;padding:12px 14px;margin:10px 0;background:var(--surface)}
.case .qt{white-space:pre-wrap;font-size:.9rem;margin:0 0 6px;color:var(--ink)}.case .ans{font-size:.88rem;color:var(--ink2);margin:2px 0}
.case .sc{font-size:.8rem;color:var(--muted);margin-top:4px}.case img{max-width:280px;margin:0 0 8px}.case .tag{font-size:.75rem;color:var(--muted)}
.lead{font-size:1.05rem;color:var(--ink2)}
"""


def table(headers, rows, best_rows=(), left_cols=()) -> str:
    """Render an HTML table with optional emphasized rows and left-aligned columns."""
    head = "".join(f'<th class="{"l" if i in left_cols else ""}">{h}</th>' for i, h in enumerate(headers))
    body = ""
    for index, row in enumerate(rows):
        css = ' class="best"' if index in best_rows else ""
        body += f"<tr{css}>" + "".join(f'<td class="{"l" if i in left_cols else ""}">{c}</td>' for i, c in enumerate(row)) + "</tr>"
    return f'<div class="tablewrap"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def figure(identifier: str, caption: str, body: str, note: str = "", wide: bool = True) -> str:
    """Wrap a chart in a titled figure with an optional note beneath it."""
    css = ' class="wide"' if wide else ""
    note_html = f'<p class="fignote">{note}</p>' if note else ""
    return f'<figure{css}><figcaption id="{identifier}">{caption}</figcaption>{body}{note_html}</figure>'


def case_card(item: dict) -> str:
    """One case-study example: optional thumbnail, question, reference and predicted answers, and scores."""
    image = f'<img class="thumb" alt="Example image" src="data:image/jpeg;base64,{item["image"]}"/>' if item.get("image") else ""
    tag = f'<div class="tag">{esc(item["category"])}</div>' if item.get("category") else ""
    return (
        f'<div class="case">{image}{tag}<p class="qt">{esc(item["question"])}</p>'
        f'<p class="ans"><b>Reference:</b> {esc(item["reference"])}</p>'
        f'<p class="ans"><b>Model answer:</b> {esc(item["prediction"])}</p>'
        f'<p class="sc">Predicted correctness, unified joint {item["joint_score"]:.2f}, unified pre-generation {item["pre_score"]:.2f}. Token confidence {item["token_confidence"]:.2f}.</p></div>'
    )


def case_group(title: str, blurb: str, items: list) -> str:
    """A titled group of case-study examples."""
    return f"<h4>{esc(title)}</h4><p class='small'>{blurb}</p>" + "".join(case_card(i) for i in items)


def build(present: dict) -> str:
    """Assemble the full report from the loaded per-dataset results."""
    names = {key: name for key, name, _ in DATASETS}
    order = [key for key, _, _ in DATASETS if key in present]
    count_word = {2: "two", 3: "three", 4: "four"}.get(len(order), str(len(order)))
    analysis = {key: present[key]["analysis"] for key in order}
    test_acc = {key: analysis[key]["splits"]["test"]["accuracy"] for key in order}
    metric = {key: present[key]["metrics"] for key in order}
    grid = analysis[order[0]]["grid"]
    boot = {key: analysis[key]["bootstrap"] for key in order}
    one_fraction = {k: analysis[k]["token_confidence_exactly_one"] for k in order}
    runs_original = parse_original_runs(ORIGINAL_REPORT)

    def at(scorer_key, key, name):
        return metric[key][scorer_key][name][0]

    def curve(key, scorer_key, field, coverage):
        return analysis[key]["scorers"][scorer_key][field][grid.index(coverage)]

    def operating(key, scorer_key, flag):
        error_rate = 1 - test_acc[key]
        capture = curve(key, scorer_key, "error_capture", flag)
        return capture, capture * error_rate / flag

    gate_rows = []
    for key in order:
        error_rate = 1 - test_acc[key]
        capture_tok = curve(key, "token_confidence", "error_capture", 0.2)
        capture_pre = curve(key, "unified_pre_generation", "error_capture", 0.2)
        capture_joint = curve(key, "unified_joint", "error_capture", 0.2)
        gate_rows.append((key, error_rate, capture_tok, capture_pre, capture_joint, capture_joint * error_rate / 0.2))
    precision_low = min(r[5] for r in gate_rows)
    precision_high = max(r[5] for r in gate_rows)

    wins, ties, losses = [], [], []
    for key in order:
        interval = boot[key]["joint_minus_separate_verifier"]["auroc"]
        (wins if interval["ci_low"] > 0 else losses if interval["ci_high"] < 0 else ties).append(key)

    def join_names(keys):
        labels = [names[k] for k in keys]
        return labels[0] if len(labels) == 1 else ", ".join(labels[:-1]) + " and " + labels[-1]

    gain_low = min(at("unified_joint", k, "correctness_auroc") - at("token_confidence", k, "correctness_auroc") for k in order)
    gain_high = max(at("unified_joint", k, "correctness_auroc") - at("token_confidence", k, "correctness_auroc") for k in order)
    input_words = {"chartqa_full": "charts", "textvqa": "photographs with text", "docvqa": "scanned pages", "scienceqa_img": "science diagrams"}
    input_list = ", ".join(input_words[k] for k in order[:-1]) + " and " + input_words[order[-1]] if len(order) > 1 else input_words[order[0]]

    toc_items = [("start", "Starting point"), ("summary", "Summary"), ("metrics", "Metrics"), ("added", "What was added"), ("datasets", "Datasets"),
                 ("unified", "Unified head"), ("results", "Results"), ("meaning", "What it means"), ("limits", "Limits"), ("next", "Next steps")]
    toc = '<nav class="toc">' + "".join(f'<a href="#{i}">{t}</a>' for i, t in toc_items) + "</nav>"

    parts = [f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Q-Head Correctness Report</title><style>{CSS}</style></head><body><main>
<h1>Predicting Answer Correctness From Frozen Latents</h1>
<p class="sub">From a single ChartQA study to {count_word} datasets and a unified head that scores an answer before and after it is generated.</p>
<p class="meta">Model: Qwen3-VL-2B. Datasets: {', '.join(names[k] for k in order)}. All results are on held-out test splits. Charts are inline SVG and follow the system light or dark setting.</p>{toc}"""]

    # ------------------------------------------------------------ 1 starting point
    parts.append("""<h2 id="start">1. Starting point: the original ChartQA study</h2>
<p class="lead">This report builds on an earlier study that asked a narrow question: before building anything that corrects a vision-language model, can we tell from the model's own internal state when it is about to be wrong? This section summarizes that study and its numbers. Everything after it is new work.</p>
<h3>What the study did</h3>
<ul>
<li><b>Data and model.</b> ChartQA, Qwen3-VL-2B, 2,500 test questions. The model answered 75.84% of them correctly, which leaves about 24% wrong answers to detect.</li>
<li><b>Features.</b> The model was run once per question and two last-layer hidden states were cached: the state at the last prompt token (before any answer, the pre-generation state) and the state at the last token after the model's own answer was appended (the candidate state). A third state, with the reference answer appended, was cached for training pairs. The language model was never updated.</li>
<li><b>Two heads.</b> A pre-generation head reads the first state and judges how likely the question is to be answered correctly. A verifier head reads the second state and judges the specific answer. Both are small networks trained on a correct or wrong label.</li>
<li><b>Training recipe.</b> Two-layer MLP (layer norm, 512 units, GELU, 10% dropout) trained with AdamW at learning rate 0.001, weight decay 0.0001, batch size 512, 20 epochs. Loss: binary cross-entropy plus 0.25 times a batch ranking loss, plus for the verifier 0.25 times a paired loss that scores the reference answer above a wrong generated one. A single temperature fitted on validation calibrated the probabilities. The test split was used once.</li>
<li><b>Sweeps.</b> 72 fits (36 per head): architecture (linear, 256-unit MLP, 512-unit MLP), learning rate (3e-4, 1e-3), ranking weight (0, 0.25) and three seeds, selected on validation error AUPRC. A second sweep added early stopping and tried five ranking weights for the verifier, over three seeds.</li></ul>
<h3>The numbers</h3>""")
    parts.append(table(["Test metric"] + [name for name, _ in ORIGINAL_COLUMNS], [[k] + v for k, v in ORIGINAL_TEST.items()]))
    parts.append('<p class="small">Original study, ChartQA test split. Errors are what a correction step would need to find, so Error AUPRC (how well wrong answers are concentrated at the top of a review queue) matters most. Section 3 defines every metric.</p>')
    auroc_values = [float(v.split()[0]) for v in ORIGINAL_TEST["Correctness AUROC"]]
    auprc_values = [float(v.split()[0]) for v in ORIGINAL_TEST["Error AUPRC"]]
    keys = ["tok", "pm", "pl", "vm", "ve"]
    original_series = [("tok", "Token confidence", "c-tok"), ("pm", "Pre-gen MLP", "c-sp"), ("pl", "Pre-gen linear probe", "c-w1"),
                       ("vm", "Verifier MLP (swept)", "c-sv"), ("ve", "Verifier, early stop", "c-up")]
    parts.append(legend([(label, css) for _, label, css in original_series]))
    parts.append(figure("fig-orig-auroc", "Correctness AUROC, original ChartQA study",
                        dot_plot([("ChartQA test", dict(zip(keys, auroc_values)))], original_series, 0.7, 0.92, "AUROC (axis starts at 0.7)", caption_id="fig-orig-auroc")))
    parts.append(figure("fig-orig-auprc", "Error AUPRC, original ChartQA study",
                        dot_plot([("ChartQA test", dict(zip(keys, auprc_values)))], original_series, 0.2, 0.78, "Error AUPRC (axis starts at 0.2)", chance={"ChartQA test": 0.2416}, caption_id="fig-orig-auprc")))
    parts.append('<p class="fignote">The dashed tick in the second chart is chance for error AUPRC, which equals the 24.2% error rate. Both axes are truncated, so read position rather than distance from the edge.</p>')
    if runs_original:
        rows = []
        for head, head_name in (("pre_generation", "Pre-generation"), ("verifier", "Verifier")):
            for arch in ("linear", "mlp_256", "mlp_512"):
                pts = [(r["error_auprc"], "c-uj" if r["ranking_weight"] == 0 else "c-sv",
                        f"{head_name} {arch}, lr {r['learning_rate']}, ranking weight {r['ranking_weight']:g}, seed {r['seed']}: {r['error_auprc']:.4f}")
                       for r in runs_original if r["head"] == head and r["architecture"] == arch]
                rows.append((f"{head_name}, {arch}", pts))
        low = min(r["error_auprc"] for r in runs_original) - 0.01
        high = max(r["error_auprc"] for r in runs_original) + 0.01
        parts.append(legend([("Ranking weight 0", "c-uj"), ("Ranking weight 0.25", "c-sv")]))
        parts.append(figure("fig-orig-sweep", "All 72 validation runs of the original sweep, by head and architecture",
                            strip_plot(rows, low, high, "Validation error AUPRC", "fig-orig-sweep"),
                            "Each dot is one run (two learning rates and three seeds per ranking weight). The linear probe is competitive for the pre-generation head, and adding the ranking loss does not lift either head. The raw table is parsed from the original report and saved as a data file alongside the results."))
    parts.append("""<h3>What the study found</h3>
<ul>
<li><b>The model's own confidence is nearly useless as a gate.</b> The geometric mean of the answer token probabilities was exactly 1.0 for 1,921 of 2,500 test answers (76.8%), including many wrong ones. Its AUROC was 0.750, and keeping its most confident half of answers only raised accuracy from 75.8% to 92.4%.</li>
<li><b>A small head on frozen states does much better.</b> The best learned scorers reached AUROC 0.89 and error AUPRC about 0.74, cut the Brier score from 0.178 to about 0.11 and ECE from 0.172 to between 0.03 and 0.04, and lifted accuracy on the most trusted half to about 97%.</li>
<li><b>Which head wins depends on the metric.</b> The linear pre-generation probe had the highest AUROC (0.895), which says expected difficulty is close to linearly readable from the question state alone. The early-stopped verifier had the highest error AUPRC (0.738) and is the one that judges a specific answer, so it is the relevant model for a correction decision.</li>
<li><b>The ranking objectives did not help.</b> Plain cross-entropy won both heads in the main sweep. The weak ranking weight (0.01) that won the early-stop sweep beat plain cross-entropy by a small margin that the study itself flagged as needing out-of-distribution validation.</li></ul>
<h3>What it left open</h3>
<p>The study ended with its own list of next steps: compare features from several layers, test the answer-induced change as an explicit feature (prompt state, answer state, and their difference), train against harder wrong answers, measure seed stability by selecting on the mean over seeds, and validate out of distribution. This report takes up three of those. It checks out of distribution on three more datasets. It selects hyperparameters on the mean of three seeds throughout. And it tests a combined prompt and answer input, by concatenation rather than by difference. Layer choice, the difference feature, and harder negatives remain open.</p>""")

    # ------------------------------------------------------------ 2 summary
    mid_accuracy = [curve(k, "unified_joint", "accuracy_at_coverage", 0.5) for k in order]
    parts.append(f"""<h2 id="summary">2. This report in brief</h2>
<div class="card summary"><ul>
<li><b>The ChartQA result transfers.</b> Across {count_word} datasets with different input types ({input_list}), the unified head raises correctness AUROC over geometric-mean token confidence by {gain_low:.2f} to {gain_high:.2f}. Token confidence is saturated everywhere: it equals 1.0 on {pct(min(one_fraction.values()), 0)} to {pct(max(one_fraction.values()), 0)} of test answers.</li>
<li><b>One head can do both jobs.</b> The unified head reads the prompt latent and the answer latent together, and with the answer half zeroed it scores a question before any answer exists. Its joint mode matches or beats the separate verifier head on every dataset: the paired bootstrap interval excludes zero in its favor on {join_names(wins) if wins else 'none of the datasets'}{', includes zero on ' + join_names(ties) if ties else ''}{', and favors the separate head on ' + join_names(losses) if losses else ''}.</li>
<li><b>It works as a gate.</b> Flagging the 20% of answers with the lowest predicted correctness captures {pct(min(r[4] for r in gate_rows), 0)} to {pct(max(r[4] for r in gate_rows), 0)} of all errors, against {pct(min(r[2] for r in gate_rows), 0)} to {pct(max(r[2] for r in gate_rows), 0)} for token confidence. Keeping only the most trusted half of answers lifts accuracy to {pct(min(mid_accuracy), 0)} to {pct(max(mid_accuracy), 0)}.</li>
<li><b>What the head learns differs by dataset.</b> On TextVQA it mostly catches broken or malformed answers, which only the answer-side state can see. On DocVQA it separates hard layouts and handwriting from easy forms. On ScienceQA it mostly learns which topics are hard, so the question alone is almost enough.</li>
<li><b>The pre-generation loss term costs almost nothing, and the pairwise loss hurts.</b> The pre-generation term lifts that mode on every dataset and moves the joint mode by less than 0.006 AUROC (validation). The pairwise reference-answer loss lowered validation AUROC on every dataset and is off in every winner.</li>
<li><b>What this does not show yet.</b> These heads detect likely errors. They do not fix them. Whether a latent correction step helps on the flagged answers is the next experiment.</li></ul></div>
{figure('fig-pipeline', 'Where the correctness head sits in the project', pipeline_diagram(), 'The language model is frozen throughout. Only the small head is trained. The dashed final box is the planned correction stage and is not part of the results here.')}""")

    # ------------------------------------------------------------ 3 metrics
    parts.append("""<h2 id="metrics">3. How to read the metrics</h2>
<p>Every learned scorer outputs a probability that the model's answer is correct. The metrics below compare those probabilities with what actually happened on the test split.</p>""")
    parts.append(table(["Metric", "Plain meaning", "Direction", "Reference point"], [
        ["Correctness AUROC", "Pick one correct and one wrong answer at random. How often does the scorer give the correct one the higher score?", "Higher is better", "0.5 is a coin flip, 1.0 is perfect"],
        ["Error AUPRC", "How well the wrong answers are packed at the top of a queue sorted from least to most trusted. This is the view that matters for a correction gate.", "Higher is better", "Chance equals the dataset's error rate"],
        ["Brier score", "Average squared gap between the predicted probability and the 0 or 1 outcome. Rewards being right and being honest about uncertainty.", "Lower is better", "Always predicting the base rate gives the baseline"],
        ["ECE", "Expected calibration error: across probability bins, the gap between what the scorer says and how often it is right.", "Lower is better", "0 is perfectly calibrated"],
        ["Pearson r", "Correlation between the predicted probability and the correct or wrong label.", "Higher is better", "0.22 is the value reported for a model's own confidence in a related study"],
        ["Accuracy at coverage", "Accuracy of the answers that remain after dropping the least trusted ones.", "Higher is better", "Full coverage equals the base accuracy"],
        ["Errors captured at a flag rate", "Share of all wrong answers that fall in the lowest-scored fraction of answers.", "Higher is better", "Random flagging captures the same share as the flag rate"],
        ["Precision of the flagged set", "Share of flagged answers that really are wrong.", "Higher is better", "Random flagging gives the base error rate"]],
        left_cols=(0, 1, 2, 3)))

    # ------------------------------------------------------------ 4 what was added
    parts.append("""<h2 id="added">4. What was added</h2>
<ul>
<li><b>Three more datasets, chosen for different inputs.</b> TextVQA, DocVQA, and ScienceQA, each with its own correctness rule, grouped splits so no image or document is shared across train, validation, and test, and an offline-tested scoring module (Section 5).</li>
<li><b>A unified head.</b> One network that reads the prompt state and the answer state together, with a loss that also keeps it useful before an answer exists (Section 6).</li>
<li><b>Automation.</b> One command per dataset submits the whole chain on the ICE cluster: build splits, baseline generation, feature extraction, both sweeps, and the analysis. The model weights are fetched once up front, caches live in scratch because the home quota is 30 GB, and GPU jobs request a flexible constraint (H200, H100, L40S, A100, or A40) because the account has no H200 partition. Every job here ran on an L40S.</li>
<li><b>Analysis tooling.</b> A script that reloads each winning head and computes the curves, reliability bins, category tables, case studies, an answer-length baseline, and paired bootstrap intervals used below, and a builder that turns those files into this report.</li></ul>""")

    # ------------------------------------------------------------ 5 datasets
    parts.append('<h2 id="datasets">5. The datasets</h2>')
    parts.append("<p>The datasets differ in what the model has to do, in what an answer looks like, and in how correctness is judged. That variety is the point: a result that holds on all of them is much harder to explain away as a property of one data source.</p>")
    overview = []
    for key in order:
        sp = analysis[key]["splits"]
        overview.append([names[key], esc(DATASET_INFO[key]["what"].split(".")[0] + "."), f"{sp['train']['count']:,} / {sp['val']['count']:,} / {sp['test']['count']:,}",
                         f"{pct(sp['train']['accuracy'])} / {pct(sp['val']['accuracy'])} / {pct(sp['test']['accuracy'])}", pct(one_fraction[key], 0)])
    parts.append(table(["Dataset", "What it asks", "Train / val / test", "Base accuracy, train / val / test", "Token confidence exactly 1.0"], overview, left_cols=(1,)))
    for key in order:
        info = DATASET_INFO[key]
        sp = analysis[key]["splits"]
        sample = (analysis[key].get("case_studies") or {}).get("confident_correct", [{}])[0]
        image = f'<img class="thumb" alt="Example image from {names[key]}" src="data:image/jpeg;base64,{sample["image"]}"/>' if sample.get("image") else ""
        caption = ""
        if sample:
            caption = (f'<p class="small" style="white-space:pre-wrap"><b>Example question.</b> {esc(sample["question"][:300])}<br><b>Reference:</b> {esc(sample["reference"])}. '
                       f'<b>Model:</b> {esc(sample["prediction"])}.</p>')
        stats = "".join(f'<div class="stat"><b>{value}</b><span>{label}</span></div>' for value, label in (
            (f"{sp['train']['count']:,}", "train questions"), (f"{sp['val']['count']:,}", "validation"), (f"{sp['test']['count']:,}", "test"),
            (pct(test_acc[key]), "base accuracy, test"), (pct(1 - test_acc[key]), "errors to detect"), (pct(one_fraction[key], 0), "token confidence = 1.0")))
        cats = analysis[key].get("categories") or []
        cat_line = ""
        if cats:
            cat_line = "<p><b>Question categories in the test split.</b> " + ", ".join(f"{esc(c['category'])} ({c['count']})" for c in cats) + ".</p>"
        parts.append(f"""<h3>{names[key]}</h3><div class="card dcard"><div>{image}{caption}</div><div>
<p><b>What it asks.</b> {esc(info['what'])}</p>
<p><b>Source.</b> {esc(info['source'])}.</p>
<p><b>Correct means.</b> {esc(info['rule'])}</p>
<p><b>Why it is here.</b> {esc(info['why'])}</p>
<p><b>Splits.</b> {esc(info['splits'])}</p>{cat_line}<div class="stats">{stats}</div></div></div>""")
    shift = {k: analysis[k]["splits"]["train"]["accuracy"] - test_acc[k] for k in order}
    big_shift = [k for k in order if abs(shift[k]) > 0.03]
    if big_shift:
        parts.append(f"<p><b>A note on the splits.</b> Base accuracy is not the same in train and test for every dataset. "
                     + " ".join(f"{names[k]} is {pct(analysis[k]['splits']['train']['accuracy'])} on its training sample against {pct(test_acc[k])} on test." for k in big_shift)
                     + " The model may have seen some of these public training sets during its own training, which we did not check, and the train sample and the carved validation split also differ in difficulty. The heads are therefore tested under a shift in base rate, and the validation split, which is drawn like the test split, is what sets the calibration temperature.</p>")

    # ------------------------------------------------------------ 6 unified head
    parts.append(f"""<h2 id="unified">6. The unified head</h2>
{figure('fig-unified', 'Unified Q-head architecture', unified_diagram(), 'Dashed boxes are the answer-side path, which is zeroed in pre-generation mode.')}
<p>Each latent is layer-normalized separately so the two are on a common scale, then concatenated with a one-bit flag that says whether an answer is present. A linear layer or small MLP maps the result to a single correctness logit. With the answer half set to zeros and the flag at 0 the same weights score a question before generation. This lets the gate run first and the answer-conditioned score be computed only when a correction might follow.</p>
<h3>Loss</h3>
<pre>L = BCE(f(prompt, answer), y)                       joint mode
  + w_pre  * BCE(f(prompt, none), y)                pre-generation mode, same weights
  + w_rank * ranking(f(prompt, answer), y)          correct above wrong, off by default
  + w_pair * softplus(f(p, a) - f(p, reference))    wrong rows only, off in all winners</pre>
<p>Both modes predict the same label, so the targets never conflict. The risk is a shortcut: the answer latent is the stronger signal, and a head trained only on joint inputs can lean on it and neglect the prompt half, which would make the pre-generation mode poor. The second term is there to prevent that. Both modes are computed on every batch, with no random dropping of the answer half, so the two terms keep a fixed ratio. Both cross-entropy terms are proper scoring rules, so calibration comes from the loss, and a per-mode temperature fitted on validation corrects what is left.</p>
<h3>Protocol</h3>
<p>Each configuration is trained on three seeds with early stopping on validation. The grid covers architecture (linear, 256-unit MLP, 512-unit MLP), learning rate (3e-4, 1e-3), pre-generation weight (0, 0.5, 1) and pair weight (0, 0.25): 36 configurations and 108 trainings per dataset. The winner is the configuration with the best mean validation score over seeds, using the average of both modes' error AUPRC with AUROC as a tiebreak. The test split is scored once, for the winner only. The separate heads from the earlier sweep are included for comparison, trained on exactly the same cached features. Learned heads are compared with plain token confidence and, in Section 7.6, with a trivial answer-length rule.</p>""")

    # ------------------------------------------------------------ 7 results
    parts.append('<h2 id="results">7. Results</h2><h3>7.1 Overview</h3>')
    parts.append("<p>The charts below put every scorer on every dataset side by side. The per-dataset sections that follow (7.2) explain each dataset's numbers in detail, including what the head catches and misses.</p>")
    rows_auroc = [(names[k], {s: metric[k][s]["correctness_auroc"][0] for s, _, _ in SCORERS}) for k in order]
    rows_auprc = [(names[k], {s: metric[k][s]["error_auprc"][0] for s, _, _ in SCORERS}) for k in order]
    chance = {names[k]: 1 - test_acc[k] for k in order}
    parts.append(scorer_legend())
    parts.append(figure("fig-auroc", "Correctness AUROC by dataset and scorer", dot_plot(rows_auroc, SCORERS, 0.6, 1.0, "AUROC (0.5 is chance, axis starts at 0.6)", caption_id="fig-auroc"),
                        "Every learned scorer sits well to the right of token confidence. The axis is truncated at 0.6, so read position, not distance from the edge."))
    parts.append(figure("fig-auprc", "Error AUPRC by dataset and scorer", dot_plot(rows_auprc, SCORERS, 0.1, 0.7, "Average precision at finding wrong answers", chance=chance, caption_id="fig-auprc"),
                        "AUPRC for errors depends on how many errors there are. The dashed tick in each row marks the chance level, which equals that dataset's error rate. The axis starts at 0.1."))
    summary_rows = [[names[key]] + [f3(metric[key][s]["correctness_auroc"][0]) for s, _, _ in SCORERS] for key in order]
    parts.append(table(["Correctness AUROC"] + [SCORER_LABEL[s] for s, _, _ in SCORERS], summary_rows))

    # 7.2 per dataset deep dives
    parts.append("<h3>7.2 Dataset by dataset</h3>")
    for key in order:
        parts.append(f"<h4 style='font-size:1.15rem;color:var(--ink);margin-top:34px'>{names[key]}</h4>")
        rows = []
        best = {}
        for name, _, direction in METRICS:
            values = {s: metric[key][s][name][0] for s, _, _ in SCORERS if s != "token_confidence"}
            best[name] = max(values, key=values.get) if direction == "higher" else min(values, key=values.get)
        for name, label, direction in METRICS:
            row = [f"{label} {'↑' if direction == 'higher' else '↓'}"]
            for s, _, _ in SCORERS:
                text = cell(metric[key][s][name])
                row.append(f"<b>{text}</b>" if best[name] == s else text)
            rows.append(row)
        parts.append(f"<p class='meta'>Test accuracy of the base model: {pct(test_acc[key])}. Bold marks the best learned scorer per row. Separate heads are single runs, unified numbers are mean ± standard deviation over three seeds.</p>")
        parts.append(table(["Metric"] + [SCORER_LABEL[s] for s, _, _ in SCORERS], rows))
        op_rows = []
        for flag in (0.1, 0.2, 0.3, 0.5):
            row = [f"{int(flag * 100)}% of answers"]
            for scorer in ("token_confidence", "unified_pre_generation", "unified_joint"):
                capture, precision = operating(key, scorer, flag)
                row.append(f"{pct(capture, 0)} / {pct(precision, 0)}")
            op_rows.append(row)
        parts.append(f"<p><b>Operating points.</b> If a fixed share of answers with the lowest score is flagged for a second look, this table gives the share of all errors captured and the share of flagged answers that really are wrong (base error rate {pct(1 - test_acc[key])}).</p>")
        parts.append(table(["Flagged", "Token confidence, captured / precision", "Unified pre-gen, captured / precision", "Unified joint, captured / precision"], op_rows))
        parts.append(dataset_discussion(key, names, metric, analysis, boot, one_fraction))
        studies = analysis[key].get("case_studies")
        if studies:
            parts.append("<p><b>Case studies.</b> Real test examples, picked by score rather than by hand. The top example in each group carries its image where one could be loaded. Scores are the unified head's predicted probability of correct.</p>")
            parts.append(case_group("Errors the head caught", "Wrong answers with the lowest predicted correctness.", studies["caught_errors"]))
            parts.append(case_group("Errors the head missed", "Wrong answers with the highest predicted correctness.", studies["missed_errors"]))
            parts.append(case_group("False alarms", "Correct answers with the lowest predicted correctness.", studies["false_alarms"]))
            parts.append(case_group("Confident and correct", "Correct answers with the highest predicted correctness.", studies["confident_correct"]))

    # 7.3 unified vs separate
    entries = []
    for key in order:
        b = boot[key]
        for comparison, label in (("joint", "joint_minus_separate_verifier"), ("pre", "unified_pre_minus_separate_pre")):
            interval = b[label]["auroc"]
            entries.append((names[key], comparison, interval["difference"], interval["ci_low"], interval["ci_high"]))
    parts.append("<h3>7.3 Unified versus separate heads</h3>")
    parts.append("<p>The question here is whether one head can replace two. Joint mode is compared with the separate verifier, and pre-generation mode with the separate pre-generation head, on the same test examples with a paired bootstrap (500 resamples; unified scores averaged over three seeds). An interval that crosses zero is a tie.</p>")
    parts.append(figure("fig-delta", "Paired AUROC difference, unified minus separate, with 95% bootstrap intervals", delta_plot(entries, "fig-delta"),
                        "Dots to the right of the zero line favor the unified head."))
    delta_rows = []
    for key in order:
        j = boot[key]["joint_minus_separate_verifier"]
        p = boot[key]["unified_pre_minus_separate_pre"]
        delta_rows.append([names[key],
                           f"{j['auroc']['difference']:+.3f} ({j['auroc']['ci_low']:+.3f}, {j['auroc']['ci_high']:+.3f})",
                           f"{j['error_auprc']['difference']:+.3f} ({j['error_auprc']['ci_low']:+.3f}, {j['error_auprc']['ci_high']:+.3f})",
                           f"{p['auroc']['difference']:+.3f} ({p['auroc']['ci_low']:+.3f}, {p['auroc']['ci_high']:+.3f})",
                           f"{p['error_auprc']['difference']:+.3f} ({p['error_auprc']['ci_low']:+.3f}, {p['error_auprc']['ci_high']:+.3f})"])
    parts.append(table(["Dataset", "Joint vs verifier, AUROC", "Joint vs verifier, error AUPRC", "Pre vs pre, AUROC", "Pre vs pre, error AUPRC"], delta_rows))
    seed_rows = []
    for key in order:
        test_runs = present[key]["unified"]["test_runs"]
        joint = [r["joint"]["correctness_auroc"] for r in test_runs]
        pre = [r["pre_generation"]["correctness_auroc"] for r in test_runs]
        epochs = [r["best_epoch"] for r in test_runs]
        seed_rows.append([names[key], present[key]["unified"]["winner"]["config"]["architecture"],
                          f"{min(joint):.3f} to {max(joint):.3f}", f"{min(pre):.3f} to {max(pre):.3f}", f"{min(epochs)} to {max(epochs)}"])
    parts.append("<p><b>Seed spread of the unified winner.</b> The same configuration trained three times from different seeds, scored on test:</p>")
    parts.append(table(["Dataset", "Winning architecture", "Joint AUROC across seeds", "Pre-gen AUROC across seeds", "Best epoch across seeds"], seed_rows))
    parts.append("<p class='small'>The spread between seeds is at most a few thousandths of AUROC, far smaller than the gaps between scorers on most datasets, so the ordering of unified against token confidence is not a seed accident. Differences between unified and separate heads of about 0.01 or less are inside the noise of single-run separate heads.</p>")

    # 7.4 using the score
    parts.append("<h3>7.4 Using the score: dropping answers and flagging errors</h3>")
    parts.append("<p>Two views of the same scores show what they are worth in use. First, if the least trusted answers are dropped, how accurate is what remains? Second, if a fixed share of answers with the lowest scores is flagged for a second look, how many of the model's errors does that share contain?</p>")
    parts.append(scorer_legend())
    panels = []
    for key in order:
        series = [(s, grid, analysis[key]["scorers"][s]["accuracy_at_coverage"]) for s, _, _ in SCORERS]
        low = min(min(v) for _, _, v in series)
        ymin = max(0.0, (int(low * 20) / 20) - 0.05)
        panels.append(line_panel(names[key], grid, series, round(ymin, 2), 1.0, 0.05 if (1 - ymin) <= 0.3 else 0.1, "Fraction of answers kept (most trusted first)", "Accuracy of kept answers"))
    parts.append(figure("fig-coverage", "Accuracy of the answers that remain as the least trusted are dropped", f'<div class="grid2">{"".join(panels)}</div>',
                        "The right edge is coverage 1.0, which equals the base accuracy. A curve that stays high toward the right means the scorer ranks wrong answers last."))
    panels = []
    for key in order:
        series = [(s, grid, analysis[key]["scorers"][s]["error_capture"]) for s, _, _ in SCORERS]
        panels.append(line_panel(names[key], grid, series, 0.0, 1.0, 0.25, "Fraction of answers flagged (least trusted first)", "Share of all errors captured", diagonal=True))
    parts.append(figure("fig-capture", "Share of all errors found in the flagged fraction of answers", f'<div class="grid2">{"".join(panels)}</div>',
                        "The dashed diagonal is what random flagging would achieve. Token confidence does find errors among the 10 to 21% of answers it scores below 1.0, then flattens, because every remaining answer is tied at 1.0 and the ties are broken at random. The learned scores keep ranking answers across the whole range."))
    gate_table = [[names[k], pct(e), pct(ct, 0), pct(cp, 0), pct(cj, 0), pct(pj, 0)] for k, e, ct, cp, cj, pj in gate_rows]
    parts.append(table(["Dataset", "Base error rate", "Errors captured, token confidence", "Errors captured, unified pre-gen mode", "Errors captured, unified joint mode", "Precision of the flagged set, joint mode"], gate_table))
    parts.append('<p class="small">All columns flag the 20% of answers with the lowest score. Precision is the share of flagged answers that are actually wrong, to be compared with the base error rate in the second column. Flagging at random would capture 20% of errors and have precision equal to that base error rate.</p>')

    # 7.5 calibration
    parts.append("<h3>7.5 Calibration</h3>")
    panels = []
    for key in order:
        series = []
        for scorer, rel in (("token_confidence", analysis[key]["reliability"]["token_confidence"]), ("unified_joint", analysis[key]["reliability"]["unified_joint"])):
            series.append((scorer, [r["mean_probability"] for r in rel], [r["accuracy"] for r in rel]))
        panels.append(line_panel(names[key], grid, series, 0.0, 1.0, 0.25, "Mean predicted probability", "Observed accuracy", diagonal=True))
    parts.append(legend([("Token confidence", "c-tok"), ("Unified, joint mode", "c-uj")]))
    parts.append(figure("fig-reliability", "Reliability: predicted probability against observed accuracy", f'<div class="grid2">{"".join(panels)}</div>',
                        "Points on the dashed diagonal are perfectly calibrated. Token confidence piles into the top-right corner; the learned head spreads across the range and tracks the diagonal after temperature scaling."))
    panels = [hist_panel(names[k], analysis[k]["histogram_unified_joint"]) for k in order]
    parts.append(legend([("Wrong answers", "c-bad"), ("Correct answers", "c-ok")]))
    parts.append(figure("fig-hist", "Where right and wrong answers land on the unified joint score", f'<div class="grid2">{"".join(panels)}</div>',
                        "Each curve is normalized within its class. Separation between the two is what AUROC measures; the overlap is the part the head cannot tell apart."))
    cat_blocks = []
    for key in order:
        cats = analysis[key].get("categories") or []
        if cats:
            rows = [(f"{c['category']} (n={c['count']})", c["accuracy"], c["mean_predicted"]) for c in cats]
            cat_blocks.append(figure(f"fig-cat-{key}", f"{names[key]}: accuracy and predicted correctness by question category", category_chart(rows, f"fig-cat-{key}"),
                                     "A gap between the two dots means the head is miscalibrated for that category."))
    if cat_blocks:
        parts.append("<h4>By question category</h4>" + "".join(cat_blocks))

    # 7.6 what drives the result
    parts.append("<h3>7.6 What drives the result</h3>")
    parts.append("<h4>Sweep landscape</h4><p>Each dot is one of the 36 unified configurations, averaged over its three seeds. A tight cluster means the result does not depend on a lucky setting.</p>")
    landscape_rows = []
    for key in order:
        pts = []
        for a in present[key]["unified"]["aggregates"]:
            c = a["config"]
            css = {"linear": "c-uj", "mlp_256": "c-sv", "mlp_512": "c-up"}[c["architecture"]]
            pts.append((a["mean_val_auroc"]["joint"], css, f"{names[key]} {c['architecture']}, lr {c['learning_rate']:g}, pre weight {c['pre_weight']:g}, pair weight {c['pair_weight']:g}: {a['mean_val_auroc']['joint']:.4f}"))
        landscape_rows.append((names[key], pts))
    lo = min(p[0] for _, pts in landscape_rows for p in pts) - 0.005
    hi = max(p[0] for _, pts in landscape_rows for p in pts) + 0.005
    parts.append(legend([("Linear", "c-uj"), ("MLP 256", "c-sv"), ("MLP 512", "c-up")]))
    parts.append(figure("fig-landscape", "Validation joint AUROC of all 36 unified configurations", strip_plot(landscape_rows, lo, hi, "Mean validation AUROC, joint mode", "fig-landscape"),
                        "Most of the scatter inside a row comes from the pair weight (the low outliers on the left) rather than from the architecture."))
    ablation_rows = []
    pair_rows = []
    arch_rows = []
    for key in order:
        aggregates = present[key]["unified"]["aggregates"]
        series = {}
        for weight in (0.0, 0.5, 1.0):
            subset = [a for a in aggregates if a["config"]["pre_weight"] == weight]
            series[weight] = max(a["mean_val_auroc"]["pre_generation"] for a in subset)
        ablation_rows.append((names[key], series))
        joint0 = max(a["mean_val_auroc"]["joint"] for a in aggregates if a["config"]["pre_weight"] == 0.0)
        joint1 = max(a["mean_val_auroc"]["joint"] for a in aggregates if a["config"]["pre_weight"] == 1.0)
        pair0 = [a["mean_val_auroc"]["joint"] for a in aggregates if a["config"]["pair_weight"] == 0.0]
        pair1 = [a["mean_val_auroc"]["joint"] for a in aggregates if a["config"]["pair_weight"] == 0.25]
        pair_rows.append([names[key], f3(sum(pair0) / len(pair0)), f3(sum(pair1) / len(pair1)), f"{(sum(pair1) / len(pair1)) - (sum(pair0) / len(pair0)):+.3f}"])
        best_arch = {arch: max(a["mean_val_auroc"]["joint"] for a in aggregates if a["config"]["architecture"] == arch) for arch in ("linear", "mlp_256", "mlp_512")}
        arch_rows.append([names[key], f3(best_arch["linear"]), f3(best_arch["mlp_256"]), f3(best_arch["mlp_512"]),
                          present[key]["unified"]["winner"]["config"]["architecture"], f"{series[0.0]:.3f} to {series[1.0]:.3f}", f"{joint1 - joint0:+.3f}"])
    parts.append("<h4>The pre-generation loss term</h4><p>The chart shows the best validation AUROC that the pre-generation mode reaches when the term is off (weight 0), half strength and full strength. The term helps on every dataset, and weight 1 was selected on every dataset.</p>")
    parts.append(legend([("Weight 0", "c-w0"), ("Weight 0.5", "c-w1"), ("Weight 1.0", "c-w2")]))
    parts.append(figure("fig-ablation", "Effect of the pre-generation loss weight on the pre-generation mode (validation)", ablation_plot(ablation_rows, "fig-ablation"),
                        "The same weights serve the joint mode, whose best validation AUROC changes by at most a few thousandths between weight 0 and weight 1 (last column of the architecture table below)."))
    parts.append("<h4>The pairwise reference-answer loss</h4><p>Mean validation joint AUROC over all configurations with the pair term off and on:</p>")
    parts.append(table(["Dataset", "Pair weight 0", "Pair weight 0.25", "Change"], pair_rows))
    parts.append("<h4>Architecture</h4><p>Best validation joint AUROC for each architecture, the architecture that won, and the pre-generation weight effect on both modes:</p>")
    parts.append(table(["Dataset", "Linear", "MLP 256", "MLP 512", "Winner", "Pre mode, weight 0 to 1", "Joint mode change"], arch_rows))
    gain_rows = []
    for key in order:
        sp_pre = at("separate_pre_generation", key, "correctness_auroc")
        sp_ver = at("separate_verifier", key, "correctness_auroc")
        up = at("unified_pre_generation", key, "correctness_auroc")
        uj = at("unified_joint", key, "correctness_auroc")
        length = analysis[key].get("answer_length_baseline")
        gain_rows.append([names[key], f3(sp_pre), f3(sp_ver), f"{sp_ver - sp_pre:+.3f}", f3(up), f3(uj), f"{uj - up:+.3f}",
                          f3(length["auroc"]) if length else "n/a", f3(at("token_confidence", key, "correctness_auroc"))])
    parts.append("<h4>How much the answer latent adds, and a trivial baseline</h4><p>The gap between a head that sees the answer and one that does not is a direct measure of what the answer side contributes. The last two columns give AUROC for a rule that scores only by answer length (shorter is more trusted) and for token confidence, to show how much of the learned signal is something simpler.</p>")
    parts.append(table(["Dataset", "Separate pre-gen", "Separate verifier", "Verifier minus pre-gen", "Unified pre-gen", "Unified joint", "Joint minus pre-gen", "Answer-length rule", "Token confidence"], gain_rows))

    # ------------------------------------------------------------ 8 meaning
    gaps = {k: at("unified_joint", k, "correctness_auroc") - at("unified_pre_generation", k, "correctness_auroc") for k in order}
    parts.append(f"""<h2 id="meaning">8. What the results mean</h2>
<h3>1. The signal is real and it transfers</h3>
<p>The learned heads beat token confidence on every dataset, and they do so on {input_list}. The model's hidden state at the end of the prompt already encodes much of how hard the question is for it, and the state after the answer encodes more about whether that specific answer is right. The ChartQA finding was not a property of charts.</p>
<h3>2. What the answer latent adds depends on how much the answer says</h3>
<p>The gap between the unified head's joint mode and its pre-generation mode is {', '.join(f"{names[k]} {gaps[k]:+.3f}" for k in order)} AUROC. Where the answer is free text, as in TextVQA and DocVQA, the answer-side state carries real extra evidence: it reflects degenerate output, run-on text, and misread strings that no question-only score can foresee. In ScienceQA the answer is a single letter among a few options, so the answer-side state has almost nothing to add and the question alone nearly saturates the signal. The benefit of an answer-conditioned verifier scales with how much information the answer itself carries.</p>
<h3>3. A pre-generation score is already worth having</h3>
<p>In pre-generation mode the head never sees the answer, yet it captures most of the benefit on two of the datasets. Because it runs before generation, it can decide whether to spend extra compute at all. The case studies show what that score is: mostly a model of question difficulty and topic, not a check on the answer.</p>
<h3>4. The head learns the model's failure modes, including ones that are not visual</h3>
<p>The caught errors on TextVQA are largely format failures (repetition loops, explanations where a short answer was asked for). The missed errors on DocVQA are largely near misses where the answer carries extra words. The ScienceQA head leans on topic. These are properties of the model plus the labeling rule, and a correction step built on this gate will inherit them. A gate that fires on a repetition loop needs a different fix than one that fires on a misread digit.</p>
<h3>5. The unified head simplifies without losing accuracy</h3>
<p>Matching or beating the separate heads with one model is a practical result: one set of weights, one cached input pair, and a choice of mode at inference. The pre-generation loss term lets the head keep a usable pre-answer score without hurting the answer-conditioned one. In pre-generation mode it is within 0.006 AUROC of the dedicated head on every dataset.</p>
<h3>6. The pairwise reference loss does not help</h3>
<p>Adding the paired loss reduced mean validation AUROC on every dataset (Section 7.6), by a large margin on DocVQA. A plausible reason, not tested here, is that the reference-answer state differs from a generated-answer state in ways unrelated to correctness, so the head can improve the pair loss by learning that difference instead. The same pattern held for the ranking loss in the original study. Plain cross-entropy is the right default.</p>
<h3>7. Calibration is good on average and uneven by category</h3>
<p>After temperature scaling the expected calibration error is small on every dataset. The category breakdown shows where it is not: on DocVQA handwritten questions accuracy is well below the head's mean prediction, so the head is overconfident exactly where the model is weakest. A gate built on this score would under-trigger there.</p>
<h3>8. Practical meaning for a correction gate</h3>
<p>If a second pass costs one extra generation, flagging 20% of answers costs 20% more compute and reaches the capture rates in Section 7.4. Precision is the other side of that trade. With the joint score, between {pct(precision_low, 0)} and {pct(precision_high, 0)} of the flagged answers are actually wrong, against base error rates of {pct(min(r[1] for r in gate_rows), 0)} to {pct(max(r[1] for r in gate_rows), 0)}. That is a {min(r[5] / r[1] for r in gate_rows):.1f} to {max(r[5] / r[1] for r in gate_rows):.1f} times enrichment, but it also means the rest of the flagged set is answers that were already right. A correction step therefore has to be safe on correct answers, a requirement that comes straight from the self-correction literature, and these precision numbers say how often it will matter.</p>
<h3>9. The label rule shapes the ceiling</h3>
<p>Several of the highest-scored errors are not visual mistakes at all. They are right answers that the labeling rule rejects, such as extra words around a correct span. No scorer can separate those from correct answers, so part of the remaining error mass is irreducible under the current rule. A softer correctness label, or a second label for "right but formatted differently", would change the numbers and may be the better target for a correction gate.</p>""")

    # ------------------------------------------------------------ 9 limits
    parts.append("""<h2 id="limits">9. Limits of these results</h2><ul>
<li><b>Detection, not correction.</b> Nothing here shows that a flagged answer can be fixed. A wrong answer the model cannot fix is still a correct detection.</li>
<li><b>One model size.</b> Only Qwen3-VL-2B was run. The 4B model is the natural check.</li>
<li><b>Carved test splits.</b> TextVQA and DocVQA test sets come from the labeled validation split because the official test answers are hidden. They are grouped by image or document, but they are not the official benchmark test sets.</li>
<li><b>Possible overlap with the model's own training data.</b> These are public benchmarks and the model may have seen their training splits. We did not test for this. It affects base accuracy more than it affects whether a head can detect errors, but it is a reason to read base rates with care.</li>
<li><b>Training subsets.</b> TextVQA and DocVQA heads train on 8,000 sampled questions rather than the full train splits.</li>
<li><b>Single separate-head runs.</b> The separate heads have no seed spread. The paired bootstrap accounts for test-set sampling but not for training-seed variation of those heads, so small differences should not be over-read.</li>
<li><b>Threshold choices in the label.</b> The correct label depends on cutoffs (two annotators for TextVQA, ANLS 0.9 for DocVQA). Other cutoffs would shift the base accuracy and the numbers somewhat.</li>
<li><b>Answer normalization quirks.</b> TextVQA scoring follows the official normalization, which strips punctuation and articles. A few answers (6 of 2,500 test answers, 0.2%) match on empty strings after normalization and are labeled correct when a human would not call them so.</li>
<li><b>Error AUPRC is noisy.</b> With 13 to 19% errors on 2,000 to 2,500 questions, error AUPRC moves by a few thousandths between seeds, so differences of that size are not evidence.</li>
<li><b>Question difficulty versus answer quality.</b> A pre-generation score can learn properties of the question set that predict errors without tracking visual evidence, and the ScienceQA case studies suggest it partly does. The planned counterfactual control (corrupting the visual evidence and checking that the score moves) has not been run.</li>
<li><b>Generation settings differ from the original study.</b> This report caps answers at 64 new tokens and uses a short-answer instruction, the original study allowed 512. Degenerate repetition loops are cut off at the cap, which may inflate the number of TextVQA errors relative to an uncapped run.</li></ul>""")

    # ------------------------------------------------------------ 10 next
    parts.append("""<h2 id="next">10. Next steps</h2><ol>
<li><b>Build the correction step and test it with the gate.</b> A first candidate is test-time latent steering that nudges the hidden state toward a higher correctness score and re-answers, compared with a random nudge of the same size and evaluated only on information available at inference.</li>
<li><b>Strengthen the head cheaply.</b> Cache several layers instead of the last one, add pooled image-token features, add the prompt-to-answer difference feature the original study suggested, and add the logged token statistics as extra inputs.</li>
<li><b>Change the target to "would a correction help".</b> Once a correction exists, train the gate on cases where it improved the answer, not just on whether the answer was wrong.</li>
<li><b>Revisit the label.</b> Try softer correctness for span-style answers and report both.</li>
<li><b>Run the counterfactual and 4B checks</b> listed above.</li></ol>""")

    # ------------------------------------------------------------ appendix
    times = dict(COMPUTE_MINUTES)
    if COMPUTE_FILE.exists():
        times.update({k: tuple(v) for k, v in json.loads(COMPUTE_FILE.read_text(encoding="utf-8")).items()})
    compute_rows = [[names[k], f"{t[0]:.0f}", f"{t[1]:.0f}", f"{t[2]:.0f}"] for k, t in times.items() if k in names]
    parts.append("<h2>Appendix: reproduction and compute</h2>")
    parts.append("<p>Run one dataset end to end from the repository root on ICE, then build the comparison and this report:</p>")
    parts.append("""<pre>bash slurm/run_qhead_pipeline.sh textvqa     # also docvqa, scienceqa_img, chartqa_full
python -m data.approach1_latent_self_correction.compare_q_heads_report
python -m data.approach1_latent_self_correction.build_report
python -m data.approach1_latent_self_correction.publish_results</pre>""")
    parts.append("<p>Wall-clock minutes per stage on one L40S (the train split dominates; val and test are shorter):</p>")
    parts.append(table(["Dataset", "Build or download", "Train baseline generation", "Train feature extraction"], compute_rows))
    parts.append('<p class="small">Each sweep (separate heads, then unified) took 2 to 5 minutes per dataset on cached features, and the analysis about 2 minutes on a CPU node. Result files: <code>q_models/&lt;dataset&gt;/sweep_results.json</code>, <code>unified_sweep_results.json</code>, <code>results/analysis_&lt;dataset&gt;.json</code>, and <code>results/chartqa_original_validation_runs.json</code> (parsed from the original report).</p>')
    parts.append("</main></body></html>")
    return "".join(parts)


def dataset_discussion(key, names, metric, analysis, boot, one_fraction) -> str:
    """Write the interpretation paragraphs for one dataset from its measured numbers."""

    def at(scorer, name):
        return metric[key][scorer][name][0]

    tok, sp, sv = at("token_confidence", "correctness_auroc"), at("separate_pre_generation", "correctness_auroc"), at("separate_verifier", "correctness_auroc")
    up, uj = at("unified_pre_generation", "correctness_auroc"), at("unified_joint", "correctness_auroc")
    j = boot[key]["joint_minus_separate_verifier"]["auroc"]
    p = boot[key]["unified_pre_minus_separate_pre"]["auroc"]
    length = analysis[key].get("answer_length_baseline")
    length_sentence = ""
    if length:
        length_sentence = (f" A rule that only looks at answer length reaches AUROC {length['auroc']:.3f}, with correct answers averaging {length['mean_length_correct']:.0f} characters "
                           f"and wrong ones {length['mean_length_wrong']:.0f}, so {'some of' if length['auroc'] > 0.6 else 'almost none of'} the answer-side signal is a length effect and the learned heads add far more than this rule.")
    cats = analysis[key].get("categories") or []
    cat_sentence = ""
    if cats:
        worst = min(cats, key=lambda c: c["accuracy"])
        best = max(cats, key=lambda c: c["accuracy"])
        cat_sentence = (f" By category, accuracy runs from {pct(worst['accuracy'], 0)} for {worst['category']} (n={worst['count']}) to {pct(best['accuracy'], 0)} for {best['category']} (n={best['count']}); "
                        f"the head predicts {pct(worst['mean_predicted'], 0)} and {pct(best['mean_predicted'], 0)} respectively.")
    jt = f"{j['difference']:+.3f} (95% interval {j['ci_low']:+.3f} to {j['ci_high']:+.3f})"
    pt = f"{p['difference']:+.3f} ({p['ci_low']:+.3f} to {p['ci_high']:+.3f})"
    opening = (f"<p><b>Reading the numbers.</b> Token confidence reaches AUROC {tok:.3f} and is exactly 1.0 on {pct(one_fraction[key], 0)} of answers. "
               f"The separate pre-generation head reaches {sp:.3f} and the separate verifier {sv:.3f}. The unified head reaches {up:.3f} in pre-generation mode and {uj:.3f} in joint mode, "
               f"a difference of {uj - up:+.3f} from seeing the answer. Against the separate heads the unified joint mode is {jt}, and the pre-generation mode {pt}.{length_sentence}{cat_sentence}</p>")
    if key == "textvqa":
        body = ("<p><b>What the head is doing.</b> The answer side matters most here: the separate verifier is well ahead of the separate pre-generation head, and the unified head shows the same gap between its two modes. "
                "The caught errors below explain why. Many are not subtle perception mistakes but degenerate outputs: a string repeated until the token limit, a run-on list where a phrase was asked for, a paragraph of explanation. "
                "Token confidence stays high on them (0.88 to 0.99 on the examples below), because each repeated token is individually likely, while the answer-side state marks them as broken. A question-only score cannot see these failures, which is why seeing the answer helps so much on this dataset.</p>"
                "<p><b>What it misses.</b> The missed errors are the opposite kind: fluent, plausible short answers that are wrong or disputed. A band name spelled differently from the annotation, a guess of a region where annotators wrote a country, a yes or no question annotated in an unusual way. Nothing in the model's state marks these as shaky, and some may be label noise rather than model error.</p>"
                "<p><b>False alarms.</b> The head also penalizes unusual answer formats and question types that are usually wrong, even when the answer is correct: digits written with spaces, and watch-time questions where the model often fails. "
                "One false alarm is a labeling quirk rather than a model success: the answer is a pair of braces, and it is labeled correct because official-style answer normalization strips punctuation, so three annotators' punctuation-only answers all normalize to the same empty string as the model's. This affects 6 of 2,500 test answers and does not change any conclusion. "
                "On this dataset the single unified head gives up nothing measurable in joint mode, but it is a little less well calibrated than the best separate verifier.</p>")
    elif key == "docvqa":
        body = ("<p><b>What the head is doing.</b> This is the hardest of the datasets to predict: the AUROC values are the lowest of the new datasets, and the unified joint mode is the clearest win over the separate verifier. "
                "The caught errors are verbose answers that run past the requested span, handwriting reads, and list-position questions that need careful reasoning over a table.</p>"
                "<p><b>The label rule is part of the story.</b> Under the strict similarity rule, many of the highest-scored 'errors' are near misses: the model returns the right span with extra words, as in a title with a date range added or a number followed by a unit word. These answers are fluent and confident, and they look just like correct ones to every scorer. "
                "They set a ceiling on how well any correctness head can do under this rule, and they are a reason to try a softer label.</p>"
                "<p><b>False alarms.</b> The head also doubts answers that the rule accepts but that differ from the reference, such as a surname spelled with a different vowel, which is arguably the head being right and the label being lenient. "
                "Handwritten questions are where the head is most overconfident, as the category chart in Section 7.5 shows.</p>"
                "<p><b>Distribution shift.</b> Base accuracy is noticeably higher on the training sample than on the held-out documents, so the head is tested on harder data than it was trained on. Its calibration holds because the temperature is fitted on a validation split drawn like the test split.</p>")
    elif key == "scienceqa_img":
        body = ("<p><b>What the head is doing.</b> This is the strongest result and the most revealing one. The pre-generation mode alone nearly matches the joint mode, and the separate verifier is the weakest learned scorer, below the separate pre-generation head. "
                "The answer is a single letter, so the answer-side state has very little to add beyond the question and image, and the verifier's last-token state is a noisier input than the prompt state.</p>"
                "<p><b>It has learned topics.</b> The caught errors and the false alarms are both dominated by genetics-cross questions (ratios and probabilities from Punnett squares), which the model often gets wrong, so the head flags that whole family, including the instances the model happens to get right. "
                "The confident-correct examples are map questions such as which continent or state is highlighted. So much of the gate is a topic detector.</p>"
                "<p><b>What it misses.</b> The missed errors are confident factual mistakes: a state capital given for the wrong state, a mislabelled animal class, a misread passage. Token confidence is 1.00 on every one of them. Factual recall errors leave no trace in the model's state that this head can find.</p>"
                "<p><b>Why this needs care.</b> A topic-level gate can look excellent because topics are easy to separate, and it would simply route every genetics question to correction. Whether that is useful depends on whether correction can fix genetics questions, which is the open experiment.</p>")
    else:
        body = ("<p>This dataset was rerun under the same protocol as the others, so its numbers are directly comparable with them and with the original study table in Section 1. "
                "Differences from that table come from generation length (64 new tokens here), single selected heads instead of the full sweeps, and the unified head being new.</p>")
    return opening + body


def main() -> None:
    """Load every available dataset's results and write the HTML report."""
    present = {}
    for key, _, _ in DATASETS:
        loaded = load_dataset_results(key)
        if loaded is None:
            print(f"[skip] {key}: results or analysis file missing")
        else:
            present[key] = loaded
    if not present:
        raise SystemExit("no dataset results found")
    runs = parse_original_runs(ORIGINAL_REPORT)
    if runs:
        ORIGINAL_RUNS_JSON.write_text(json.dumps(runs, indent=2) + "\n", encoding="utf-8")
        print(f"[data] wrote {ORIGINAL_RUNS_JSON.name} ({len(runs)} runs)")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build(present), encoding="utf-8")
    print(f"[report] wrote {OUTPUT} with {', '.join(present)}")


if __name__ == "__main__":
    main()
