# build_failure_pool.py
#
# Builds the failure-inclusive training pool the Approach 2 verifier
# needs. Unlike a standard dataset download, this pool is generated by
# running the policy model (see models/run_inference.py) and keeping
# every candidate trace it produces, correct or not, rather than
# discarding the wrong ones. Training the verifier only on successful
# rollouts would never teach it what a bad candidate looks like.
#
# The candidate sampling function below is a placeholder. The exact
# format a candidate should take (a crop, a bounding box, a full answer)
# is still an open design choice for this approach, so this script sets
# up the pipeline shape without hardcoding that decision.

import argparse
import os

from data.approach2_verifier_reranking.dataset_config import FAILURE_POOL_DIR_NAME
from data.common.utils import read_jsonl, write_jsonl
from models.load_model import load_qwen3_vl

PROCESSED_DIR = os.path.join(os.path.dirname(__file__), "processed")
POOL_DIR = os.path.join(os.path.dirname(__file__), FAILURE_POOL_DIR_NAME)


def sample_candidates(model, processor, example: dict, k: int) -> list:
    """Sample k candidate traces from the policy model for one example.

    Each candidate should end up as a dictionary holding the generated
    answer or grounding box together with whether it matched the ground
    truth, so the verifier can later be trained on both correct and
    incorrect candidates from the same pool. The generation call itself
    is left as a placeholder until the candidate format for this
    experiment (crop, box, or answer) is decided; wire it up using the
    same chat template and generation logic as models/run_inference.py.
    """
    candidates = []
    for _ in range(k):
        candidates.append(
            {
                "prediction": None,
                "is_correct": None,
            }
        )
    return candidates


def build_pool_for_dataset(name: str, size: str, k: int) -> None:
    """Build a failure-inclusive candidate pool for one preprocessed dataset.

    Reads the normalized examples produced by preprocess.py, samples k
    candidates per example from the given model size, and writes the
    full set of candidates, including the wrong ones, to the pool
    directory for the verifier to train on later.
    """
    in_path = os.path.join(PROCESSED_DIR, f"{name}_train.jsonl")
    if not os.path.exists(in_path):
        print(f"[skip] {name}: run preprocess.py first, {in_path} not found")
        return

    examples = read_jsonl(in_path)
    model, processor = load_qwen3_vl(size)

    pool_records = []
    for example in examples:
        candidates = sample_candidates(model, processor, example, k)
        pool_records.append({**example, "candidates": candidates})

    out_path = os.path.join(POOL_DIR, f"{name}_pool.jsonl")
    write_jsonl(pool_records, out_path)
    print(f"[done] wrote {len(pool_records)} pooled examples to {out_path}")


def main() -> None:
    """Parse command line arguments and build the failure pool for one dataset."""
    parser = argparse.ArgumentParser(description="Build the Approach 2 verifier failure pool.")
    parser.add_argument(
        "--dataset", required=True, help="Dataset name, matching a key in dataset_config.py."
    )
    parser.add_argument(
        "--size", choices=["2b", "4b"], default="2b", help="Policy model size to sample from."
    )
    parser.add_argument("--k", type=int, default=4, help="Number of candidates to sample per example.")
    args = parser.parse_args()

    build_pool_for_dataset(args.dataset, args.size, args.k)


if __name__ == "__main__":
    main()
